// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exercises.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createExercise = `-- name: CreateExercise :one
INSERT INTO exercises(name, user_id, description, media_urls)
VALUES (
		$1,
		$2,
		$3,
		$4
		)
RETURNING id, name, user_id, description, media_urls, created_at
`

type CreateExerciseParams struct {
	Name        string
	UserID      uuid.UUID
	Description string
	MediaUrls   []string
}

func (q *Queries) CreateExercise(ctx context.Context, arg CreateExerciseParams) (Exercise, error) {
	row := q.db.QueryRowContext(ctx, createExercise,
		arg.Name,
		arg.UserID,
		arg.Description,
		pq.Array(arg.MediaUrls),
	)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.Description,
		pq.Array(&i.MediaUrls),
		&i.CreatedAt,
	)
	return i, err
}

const getExerciseById = `-- name: GetExerciseById :one
SELECT exercises.id, exercises.name, exercises.user_id, exercises.description, exercises.media_urls, exercises.created_at, users.name as author_name
FROM exercises
LEFT JOIN users ON exercises.user_id = users.id
WHERE exercises.id = $1
`

type GetExerciseByIdRow struct {
	ID          uuid.UUID
	Name        string
	UserID      uuid.UUID
	Description string
	MediaUrls   []string
	CreatedAt   time.Time
	AuthorName  sql.NullString
}

func (q *Queries) GetExerciseById(ctx context.Context, id uuid.UUID) (GetExerciseByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getExerciseById, id)
	var i GetExerciseByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.Description,
		pq.Array(&i.MediaUrls),
		&i.CreatedAt,
		&i.AuthorName,
	)
	return i, err
}

const getExercises = `-- name: GetExercises :many
SELECT exercises.id, exercises.name, exercises.user_id, exercises.description, exercises.media_urls, exercises.created_at, users.name as author_name
FROM exercises
LEFT JOIN users ON exercises.user_id = users.id
`

type GetExercisesRow struct {
	ID          uuid.UUID
	Name        string
	UserID      uuid.UUID
	Description string
	MediaUrls   []string
	CreatedAt   time.Time
	AuthorName  sql.NullString
}

func (q *Queries) GetExercises(ctx context.Context) ([]GetExercisesRow, error) {
	rows, err := q.db.QueryContext(ctx, getExercises)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExercisesRow
	for rows.Next() {
		var i GetExercisesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UserID,
			&i.Description,
			pq.Array(&i.MediaUrls),
			&i.CreatedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
