// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Exercise struct {
	ID          uuid.UUID
	Name        string
	UserID      uuid.UUID
	Description string
	MediaUrls   []string
	CreatedAt   time.Time
}

type Post struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Content      string
	MediaUrls    []string
	Visibility   string
	LikeCount    int32
	CommentCount int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type PostsComment struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	PostID    uuid.UUID
	Content   string
	CreatedAt time.Time
}

type PostsLike struct {
	UserID    uuid.UUID
	PostID    uuid.UUID
	CreatedAt sql.NullTime
}

type Program struct {
	ID          uuid.UUID
	Name        string
	UserID      uuid.UUID
	Description string
	MediaUrls   []string
	Visibility  string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type ProgramDay struct {
	ID          uuid.UUID
	ProgramID   uuid.UUID
	Name        string
	Description string
	DayOrder    int32
	CreatedAt   sql.NullTime
}

type ProgramLift struct {
	ID           uuid.UUID
	ProgramDayID uuid.UUID
	ExerciseID   uuid.UUID
	Description  string
	LiftOrder    int32
	Sets         int32
	Reps         int32
	CreatedAt    sql.NullTime
}

type RefreshToken struct {
	ID        uuid.UUID
	CreatedAt sql.NullTime
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Name           string
	Email          string
	Bio            string
	HashedPassword string
	Premium        bool
}

type UserFollow struct {
	FollowerID uuid.UUID
	FollowedID uuid.UUID
	CreatedAt  sql.NullTime
}
