// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Post struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Content      string
	MediaUrls    []string
	Visibility   string
	LikeCount    int32
	CommentCount int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type PostsComment struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	PostID    uuid.UUID
	Content   string
	CreatedAt time.Time
}

type PostsLike struct {
	UserID    uuid.UUID
	PostID    uuid.UUID
	CreatedAt sql.NullTime
}

type RefreshToken struct {
	ID        uuid.UUID
	CreatedAt sql.NullTime
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Name           string
	Email          string
	Bio            string
	HashedPassword string
	Premium        bool
}

type UserFollow struct {
	FollowerID uuid.UUID
	FollowedID uuid.UUID
	CreatedAt  sql.NullTime
}
