// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts(user_id, content, media_urls, visibility)
VALUES (
		$1,
		$2,
		$3,
		$4
		)
RETURNING id, user_id, content, media_urls, visibility, like_count, comment_count, created_at, updated_at
`

type CreatePostParams struct {
	UserID     uuid.UUID
	Content    string
	MediaUrls  []string
	Visibility string
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.UserID,
		arg.Content,
		pq.Array(arg.MediaUrls),
		arg.Visibility,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		pq.Array(&i.MediaUrls),
		&i.Visibility,
		&i.LikeCount,
		&i.CommentCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFollowedPosts = `-- name: GetFollowedPosts :many
SELECT posts.id, users.id as author_id, users.name as author_name, posts.created_at, posts.visibility, posts.media_urls, posts.content
FROM posts
INNER JOIN user_follows ON posts.user_id = user_follows.followed_id
INNER JOIN users ON post.user_id = users.id
WHERE user_follows.follower_id = $1
AND posts.visibility IN ('public', 'followers')
ORDER BY posts.created_at DESC
`

type GetFollowedPostsRow struct {
	ID         uuid.UUID
	AuthorID   uuid.UUID
	AuthorName string
	CreatedAt  time.Time
	Visibility string
	MediaUrls  []string
	Content    string
}

func (q *Queries) GetFollowedPosts(ctx context.Context, followerID uuid.UUID) ([]GetFollowedPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, getFollowedPosts, followerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFollowedPostsRow
	for rows.Next() {
		var i GetFollowedPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.AuthorName,
			&i.CreatedAt,
			&i.Visibility,
			pq.Array(&i.MediaUrls),
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPost = `-- name: GetPost :one
SELECT id, user_id, content, media_urls, visibility, like_count, comment_count, created_at, updated_at FROM posts
WHERE id = $1
`

func (q *Queries) GetPost(ctx context.Context, id uuid.UUID) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		pq.Array(&i.MediaUrls),
		&i.Visibility,
		&i.LikeCount,
		&i.CommentCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
