// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, created_at, updated_at, name, email, bio, hashed_password)
VALUES (
		gen_random_uuid(),
		NOW(),
		NOW(),
		$1,
		$2,
		$3,
		$4
)
RETURNING id, created_at, updated_at, name, email, bio, hashed_password, premium
`

type CreateUserParams struct {
	Name           string
	Email          string
	Bio            string
	HashedPassword string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Bio,
		arg.HashedPassword,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Email,
		&i.Bio,
		&i.HashedPassword,
		&i.Premium,
	)
	return i, err
}

const followUser = `-- name: FollowUser :exec
INSERT INTO user_follows(follower_id, followed_id)
VALUES (
		$1,
		$2
		)
`

type FollowUserParams struct {
	FollowerID uuid.UUID
	FollowedID uuid.UUID
}

func (q *Queries) FollowUser(ctx context.Context, arg FollowUserParams) error {
	_, err := q.db.ExecContext(ctx, followUser, arg.FollowerID, arg.FollowedID)
	return err
}

const getFollowedUsers = `-- name: GetFollowedUsers :many
SELECT users.id, users.name, users.created_at, users.updated_at, users.bio, users.premium
FROM users
INNER JOIN user_follows ON users.id = user_follows.followed_id
WHERE user_follows.follower_id = $1
`

type GetFollowedUsersRow struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	Bio       string
	Premium   bool
}

func (q *Queries) GetFollowedUsers(ctx context.Context, followerID uuid.UUID) ([]GetFollowedUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getFollowedUsers, followerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFollowedUsersRow
	for rows.Next() {
		var i GetFollowedUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Bio,
			&i.Premium,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, created_at, updated_at, name, email, bio, premium
FROM users
WHERE id = $1
`

type GetUserRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Email     string
	Bio       string
	Premium   bool
}

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Email,
		&i.Bio,
		&i.Premium,
	)
	return i, err
}

const getUserLogin = `-- name: GetUserLogin :one
SELECT id, created_at, updated_at, name, email, bio, premium, hashed_password
FROM users
WHERE email = $1
`

type GetUserLoginRow struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Name           string
	Email          string
	Bio            string
	Premium        bool
	HashedPassword string
}

func (q *Queries) GetUserLogin(ctx context.Context, email string) (GetUserLoginRow, error) {
	row := q.db.QueryRowContext(ctx, getUserLogin, email)
	var i GetUserLoginRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Email,
		&i.Bio,
		&i.Premium,
		&i.HashedPassword,
	)
	return i, err
}

const updateBio = `-- name: UpdateBio :exec
UPDATE users
SET bio = $2,
updated_at = Now()
WHERE id = $1
`

type UpdateBioParams struct {
	ID  uuid.UUID
	Bio string
}

func (q *Queries) UpdateBio(ctx context.Context, arg UpdateBioParams) error {
	_, err := q.db.ExecContext(ctx, updateBio, arg.ID, arg.Bio)
	return err
}
