// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workouts.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createWorkout = `-- name: CreateWorkout :one
INSERT INTO workouts(user_id, program_day_id)
VALUES (
		$1,
		$2
		)
RETURNING id, user_id, program_day_id, created_at
`

type CreateWorkoutParams struct {
	UserID       uuid.UUID
	ProgramDayID uuid.UUID
}

func (q *Queries) CreateWorkout(ctx context.Context, arg CreateWorkoutParams) (Workout, error) {
	row := q.db.QueryRowContext(ctx, createWorkout, arg.UserID, arg.ProgramDayID)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProgramDayID,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkoutLift = `-- name: CreateWorkoutLift :one
INSERT INTO users_lifts(user_id, workout_id, exercise_id, weight, sets, reps, lift_order)
VALUES (
		$1,
		$2,
		$3,
		$4,
		$5,
		$6,
		$7)
RETURNING id, user_id, exercise_id, workout_id, created_at, weight, sets, reps, lift_order
`

type CreateWorkoutLiftParams struct {
	UserID     uuid.UUID
	WorkoutID  uuid.UUID
	ExerciseID uuid.UUID
	Weight     int32
	Sets       int32
	Reps       int32
	LiftOrder  int32
}

func (q *Queries) CreateWorkoutLift(ctx context.Context, arg CreateWorkoutLiftParams) (UsersLift, error) {
	row := q.db.QueryRowContext(ctx, createWorkoutLift,
		arg.UserID,
		arg.WorkoutID,
		arg.ExerciseID,
		arg.Weight,
		arg.Sets,
		arg.Reps,
		arg.LiftOrder,
	)
	var i UsersLift
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExerciseID,
		&i.WorkoutID,
		&i.CreatedAt,
		&i.Weight,
		&i.Sets,
		&i.Reps,
		&i.LiftOrder,
	)
	return i, err
}

const getUsersLiftsByExercise = `-- name: GetUsersLiftsByExercise :many
SELECT id, user_id, exercise_id, workout_id, created_at, weight, sets, reps, lift_order FROM users_lifts
WHERE exercise_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetUsersLiftsByExercise(ctx context.Context, exerciseID uuid.UUID) ([]UsersLift, error) {
	rows, err := q.db.QueryContext(ctx, getUsersLiftsByExercise, exerciseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsersLift
	for rows.Next() {
		var i UsersLift
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExerciseID,
			&i.WorkoutID,
			&i.CreatedAt,
			&i.Weight,
			&i.Sets,
			&i.Reps,
			&i.LiftOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersWorkouts = `-- name: GetUsersWorkouts :many
SELECT id, user_id, program_day_id, created_at FROM workouts
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetUsersWorkouts(ctx context.Context, userID uuid.UUID) ([]Workout, error) {
	rows, err := q.db.QueryContext(ctx, getUsersWorkouts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workout
	for rows.Next() {
		var i Workout
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProgramDayID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkoutByID = `-- name: GetWorkoutByID :one
SELECT id, user_id, program_day_id, created_at FROM workouts
WHERE id = $1
`

func (q *Queries) GetWorkoutByID(ctx context.Context, id uuid.UUID) (Workout, error) {
	row := q.db.QueryRowContext(ctx, getWorkoutByID, id)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProgramDayID,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkoutLifts = `-- name: GetWorkoutLifts :many
SELECT id, user_id, exercise_id, workout_id, created_at, weight, sets, reps, lift_order FROM users_lifts
WHERE workout_id = $1
ORDER BY lift_order ASC
`

func (q *Queries) GetWorkoutLifts(ctx context.Context, workoutID uuid.UUID) ([]UsersLift, error) {
	rows, err := q.db.QueryContext(ctx, getWorkoutLifts, workoutID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsersLift
	for rows.Next() {
		var i UsersLift
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExerciseID,
			&i.WorkoutID,
			&i.CreatedAt,
			&i.Weight,
			&i.Sets,
			&i.Reps,
			&i.LiftOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
